# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "bs-platform-9.0.2" = {
      name = "bs-platform";
      packageName = "bs-platform";
      version = "9.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bs-platform/-/bs-platform-9.0.2.tgz";
        sha512 = "Ye9JqJ4Oa7mcjjoOVRYI8Uc2Cf8N7jQLWDcdUplY7996d/YErSR7WitmV7XnSwr4EvdrbwjEsg1NxNjUQv3ChA==";
      };
    };
    "gentype-3.44.0" = {
      name = "gentype";
      packageName = "gentype";
      version = "3.44.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/gentype/-/gentype-3.44.0.tgz";
        sha512 = "+nbBrz3LO+OpiLr4tw8Mdy8LB/4vhGRfmiXMdZZFDNbK9k09KWIe071Zl8sOBlL+CAt7Nl1DyRVAaruhb9wuOw==";
      };
    };
    "vue-2.6.12" = {
      name = "vue";
      packageName = "vue";
      version = "2.6.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/vue/-/vue-2.6.12.tgz";
        sha512 = "uhmLFETqPPNyuLLbsKz6ioJ4q7AZHzD8ZVFNATNyICSZouqP2Sz0rotWQC8UNBF6VGSCs5abnKJoStA6JbCbfg==";
      };
    };
  };
  args = {
    name = "chrysto";
    packageName = "chrysto";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."bs-platform-9.0.2"
      sources."gentype-3.44.0"
      sources."vue-2.6.12"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Pedagogical support for a talk on the history of cryptography";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
