// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Char from "../../../../../../../usr/local/lib/node_modules/bs-platform/lib/es6/char.js";
import * as Pervasives from "../../../../../../../usr/local/lib/node_modules/bs-platform/lib/es6/pervasives.js";
import * as Caml_option from "../../../../../../../usr/local/lib/node_modules/bs-platform/lib/es6/caml_option.js";

function index(c) {
  var diff = c - /* 'a' */97 | 0;
  if (diff >= 0 && diff < 26) {
    return diff;
  }
  
}

function unwrap(v) {
  if (v !== undefined) {
    return Caml_option.valFromOption(v);
  } else {
    return Pervasives.failwith("unwrap");
  }
}

function from_index(i) {
  return Char.chr(/* 'a' */97 + i | 0);
}

function is_uppercase(c) {
  if (c >= /* 'A' */65) {
    return c <= /* 'Z' */90;
  } else {
    return false;
  }
}

export {
  index ,
  unwrap ,
  from_index ,
  is_uppercase ,
  
}
/* No side effect */
